on:
  push:
    branches: [ dev, main ]
  pull_request:

name: Rust Format

jobs:
  fmt:
    name: Check Rust
    runs-on: ubuntu-latest
    steps:

      - name: Setup EDAMAME Posture
        uses: edamametechnologies/edamame_posture_action@v0
        with:
          edamame_user: ${{ vars.EDAMAME_POSTURE_USER }}
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
          edamame_id: ${{ github.run_id }}
          checkout: true
          
      - run: rustup component add rustfmt

      - run: |
          # Install protobuf
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Check code format
        run: |
          cargo fmt --all -- --check


