on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rustfmt
        run: |
          rustup component add rustfmt

      - run: |
          # Install protobuf
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup for edamame_foundation
        shell: bash
        run: |
          cd ..
          git clone --branch ${{ steps.extract_branch.outputs.branch }} https://github.com/edamametechnologies/edamame_foundation.git

      - name: Check code format
        run: |
          cargo fmt --all -- --check


