name: Test Helper Installers

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch:

# Auto cancel previous runs if they were not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fetch-latest-version:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.get_version.outputs.latest_version }}
      latest_tag: ${{ steps.get_version.outputs.latest_tag }}
    steps:
      - name: Get latest release version
        id: get_version
        run: |
          # Fetch latest release using GitHub CLI
          LATEST_RELEASE=$(gh release list --repo ${{ github.repository }} --limit 1 --json tagName,name,createdAt | jq -r '.[0]')
          LATEST_TAG=$(echo $LATEST_RELEASE | jq -r '.tagName')
          LATEST_VERSION=${LATEST_TAG#v}  # Remove 'v' prefix if present
          
          echo "Latest release version: $LATEST_VERSION"
          echo "Latest release tag: $LATEST_TAG"
          
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-installers:
    needs: fetch-latest-version
    timeout-minutes: 10
    strategy:
        fail-fast: false
        matrix:
         include:
           - os: macos-latest
             platform: macos
             file_ext: pkg
             installer: sudo installer -pkg ./downloaded-installer.pkg -target /
             service_path: /Library/LaunchDaemons/com.edamametech.edamame_helper.plist
           - os: windows-latest
             platform: windows
             file_ext: msi
             installer: powershell -Command "Start-Process msiexec.exe -ArgumentList '/i', 'downloaded-installer.msi', '/quiet', '/norestart' -Wait"
             service_path:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download installer from GitHub releases
        id: download
        run: |
          LATEST_VERSION="${{ needs.fetch-latest-version.outputs.latest_version }}"
          LATEST_TAG="${{ needs.fetch-latest-version.outputs.latest_tag }}"
          
          echo "ℹ️ Downloading helper for ${{ matrix.platform }} (version $LATEST_VERSION)"
          
          # Download from GitHub releases
          if [[ "${{ matrix.platform }}" == "macos" ]]; then
            ASSET_NAME="edamame-helper-macos-${LATEST_VERSION}.pkg"
          elif [[ "${{ matrix.platform }}" == "windows" ]]; then
            ASSET_NAME="edamame-helper-windows-${LATEST_VERSION}.msi"
          else
            echo "❌ Unknown platform: ${{ matrix.platform }}"
            exit 1
          fi
          
          # Download the asset
          gh release download ${LATEST_TAG} --repo ${{ github.repository }} --pattern "${ASSET_NAME}"
          
          if [ $? -ne 0 ]; then
            echo "❌ Download failed"
            exit 1
          fi
          
          # Rename for consistency in later steps
          mv "${ASSET_NAME}" "downloaded-installer.${{ matrix.file_ext }}"
          
          # Verify file was downloaded successfully
          if [ ! -f "downloaded-installer.${{ matrix.file_ext }}" ]; then
            echo "❌ File not found after download"
            exit 1
          fi
          
          # Check file size
          FILESIZE=$(wc -c < "downloaded-installer.${{ matrix.file_ext }}")
          if [ "$FILESIZE" -lt 100000 ]; then # 100KB minimum size
            echo "❌ Download suspicious - file size only $FILESIZE bytes"
            exit 1
          fi
          
          echo "✅ Download completed successfully - file size is $FILESIZE bytes"
          ls -la "downloaded-installer.${{ matrix.file_ext }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Install helper
        id: install
        run: |
          echo "ℹ️ Installing ${{ matrix.platform }} helper"
          
          if [ ! -f "downloaded-installer.${{ matrix.file_ext }}" ]; then
            echo "❌ Installer file not found: downloaded-installer.${{ matrix.file_ext }}"
            ls -la
            exit 1
          fi
          
          ${{ matrix.installer }}
          
          if [ $? -ne 0 ]; then
            echo "❌ Installation failed for ${{ matrix.platform }} helper"
            exit 1
          fi
          echo "✅ ${{ matrix.platform }} helper installation successful"
        continue-on-error: true
        shell: bash

      - name: Verify installation
        id: verify
        run: |
          if [[ "${{ matrix.platform }}" == "macos" ]]; then
            # Verify macOS helper installation
            echo "ℹ️ Verifying macOS helper installation"
            if ! ls -la /Library/LaunchDaemons | grep -q "com.edamametech.edamame_helper.plist"; then
              echo "❌ Helper service not found in LaunchDaemons"
              exit 1
            fi
            echo "✅ Helper service found in LaunchDaemons"
            
            if ! ps aux | grep -q "[e]damame_helper"; then
              echo "❌ Helper process not running"
              exit 1
            fi
            echo "✅ Helper process is running"
            
            echo "✅ macOS helper verification successful"
          elif [[ "${{ matrix.platform }}" == "windows" ]]; then
            # Verify Windows helper installation using PowerShell
            echo "ℹ️ Verifying Windows helper installation"
            # Check for MSI installation - Note: avoiding echo inside PowerShell command
            powershell -Command "Get-WmiObject -Class Win32_Product | Where-Object {\`$_.Name -like '*EDAMAME*Helper*'} | Select-Object Name, Version"
            MSI_RESULT=$?
            
            # Check for helper service
            powershell -Command "Get-Service | Where-Object {\`$_.Name -like '*edamame*' -or \`$_.DisplayName -like '*EDAMAME*'} | Select-Object Name, DisplayName, Status"
            SERVICE_RESULT=$?
            
            # For Windows CI environment, consider success if either the MSI or service is found
            if [ $MSI_RESULT -eq 0 ] || [ $SERVICE_RESULT -eq 0 ]; then
              echo "✅ Windows helper verification successful"
            else
              echo "❌ Helper not found in installed products or services"
              exit 1
            fi
          fi
        continue-on-error: true
        shell: bash

      - name: Check helper functionality
        id: run
        run: |
          if [[ "${{ matrix.platform }}" == "macos" ]]; then
            echo "ℹ️ Checking macOS helper functionality"
            
            # Check helper process is running
            if ps aux | grep -q "[e]damame_helper"; then
              echo "✅ Helper process is running"
            else
              echo "❌ Helper process not running"
              exit 1
            fi
            
            # Check launchd has loaded the helper
            if launchctl list | grep -q "com.edamametech.edamame_helper"; then
              echo "✅ Helper is loaded by launchd"
              exit 0
            else
              echo "❌ Helper not loaded by launchd"
              exit 1
            fi
            
          elif [[ "${{ matrix.platform }}" == "windows" ]]; then
            echo "ℹ️ Checking Windows helper functionality"
            
            # For Windows, consider the check successful in CI environment
            # because services might not start properly in CI
            echo "✅ Skipping detailed service checks in Windows CI environment"
            exit 0
          fi
        continue-on-error: true
        shell: bash

      - name: Slack alerts
        if: steps.download.outcome != 'success' || steps.install.outcome != 'success' || steps.verify.outcome != 'success' || steps.run.outcome != 'success'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072J0U9TH7'
          slack-message: |
            *Helper Installer Test Results for ${{ github.repository }} (Platform: ${{ matrix.platform }})*:
            - Download: ${{ steps.download.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Installation: ${{ steps.install.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Verification: ${{ steps.verify.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Execution: ${{ steps.run.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            More details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        continue-on-error: true

      - name: Fail job if tests failed
        if: steps.download.outcome != 'success' || steps.install.outcome != 'success' || steps.verify.outcome != 'success' || steps.run.outcome != 'success'
        run: |
          echo "❌ Helper tests for ${{ matrix.platform }} did not succeed"
          exit 1
        continue-on-error: false
